name: chatify

services:
  postgres:
    restart: always
    image: postgres:16.8-alpine3.20
    container_name: chatify-postgres
    environment:
      POSTGRES_DB: chatify
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_user
      - db_password
    networks:
      - backend_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chatify-backend
    env_file: "./backend/.envrc"
    environment:
      APP_ENV: production
    networks:
      - backend_network
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8084:8084"

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chatify-frontend
    env_file: "./frontend/.env.local"
    depends_on:
      - postgres
      - backend
    ports:
      - "3000:3000"

secrets:
  db_user:
    file: db_user.txt
  db_password:
    file: db_password.txt

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge
