// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID       int64
	Username string
	Email    string
	ClerkID  string
	ImageUrl pgtype.Text
}
