// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: messages.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :exec
WITH messages_id AS (
    INSERT INTO messages (
        sender_id, conversation_id, type, content
    ) VALUES (
        $1, $2, $3, $4
    )
    RETURNING id
)
UPDATE conversations
SET last_message_id = (SELECT id FROM messages_id)
WHERE conversations.id = $2
`

type CreateMessageParams struct {
	SenderID int64   `json:"sender_id"`
	ID       int64   `json:"id"`
	Type     *string `json:"type"`
	Content  *string `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.Exec(ctx, createMessage,
		arg.SenderID,
		arg.ID,
		arg.Type,
		arg.Content,
	)
	return err
}

const getMessages = `-- name: GetMessages :many
SELECT u.id as user_id, u.username, u.image_url, u.email, m.id as message_id, m.conversation_id as conversation_id ,m.type, m.content, m.created_at FROM messages m
JOIN users u ON u.id = m.sender_id
WHERE conversation_id = $1
ORDER BY m.created_at DESC
`

type GetMessagesRow struct {
	UserID         int64              `json:"user_id"`
	Username       string             `json:"username" validate:"required,min=1,max=100"`
	ImageUrl       *string            `json:"image_url" validate:"required,url"`
	Email          string             `json:"email" validate:"required,email,max=255"`
	MessageID      int64              `json:"message_id"`
	ConversationID int64              `json:"conversation_id"`
	Type           *string            `json:"type"`
	Content        *string            `json:"content"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetMessages(ctx context.Context, conversationID int64) ([]GetMessagesRow, error) {
	rows, err := q.db.Query(ctx, getMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesRow
	for rows.Next() {
		var i GetMessagesRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.ImageUrl,
			&i.Email,
			&i.MessageID,
			&i.ConversationID,
			&i.Type,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
