// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID       int64       `json:"id"`
	Username string      `json:"username"`
	Email    string      `json:"email"`
	ClerkID  string      `json:"clerk_id"`
	ImageUrl pgtype.Text `json:"image_url"`
}
