// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID       int64       `db:"id" json:"id"`
	Username string      `db:"username" json:"username" validate:"required"`
	Email    string      `db:"email" json:"email"`
	ClerkID  string      `db:"clerk_id" json:"clerk_id"`
	ImageUrl pgtype.Text `db:"image_url" json:"image_url"`
}
