// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package store

type User struct {
	ID       int64   `json:"id"`
	Username string  `json:"username" validate:"required,min=1,max=100"`
	Email    string  `json:"email" validate:"required,email,max=255"`
	ClerkID  string  `json:"clerk_id" validate:"required"`
	ImageUrl *string `json:"image_url" validate:"required,url"`
}
